# Generated by Django 5.2 on 2025-04-03 22:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'iso_code',
                    models.CharField(
                        help_text='Currency Code (ISO 4217)',
                        max_length=3,
                        verbose_name='iso code',
                    ),
                ),
                (
                    'rate_datetime',
                    models.DateTimeField(
                        help_text='Datetime of the rate', verbose_name='rate datetime'
                    ),
                ),
                (
                    'rate_type',
                    models.CharField(
                        help_text='Bank Rate type: B - buy, S - sell',
                        max_length=1,
                        verbose_name='Curency rate',
                    ),
                ),
                (
                    'rate',
                    models.DecimalField(
                        decimal_places=7,
                        help_text='Bank Rate',
                        max_digits=15,
                        verbose_name='Curency rate',
                    ),
                ),
                (
                    'rate_delta',
                    models.DecimalField(
                        decimal_places=7,
                        help_text='Bank Rate',
                        max_digits=15,
                        verbose_name='rate delta',
                    ),
                ),
                (
                    'rate_nbu',
                    models.DecimalField(
                        decimal_places=7,
                        help_text='Technical National Bank Rate',
                        max_digits=15,
                        verbose_name='rate NBU',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created'),
                ),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
            },
        ),
        migrations.CreateModel(
            name='P24ApiSession',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'token',
                    models.CharField(
                        db_index=True, max_length=40, verbose_name='Token'
                    ),
                ),
                ('roles', models.TextField(verbose_name='roles')),
                (
                    'expires_in',
                    models.CharField(max_length=20, verbose_name='expires_in str'),
                ),
                (
                    'expires_at',
                    models.DateTimeField(db_index=True, verbose_name='expires at'),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='created at'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(auto_now=True, verbose_name='updated at'),
                ),
            ],
            options={
                'verbose_name': 'P24 Api Session',
                'verbose_name_plural': 'P24 Api Sessions',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'info_number',
                    models.CharField(
                        db_index=True,
                        help_text='payment number',
                        max_length=40,
                        verbose_name='number',
                    ),
                ),
                (
                    'info_postdate',
                    models.DateTimeField(
                        help_text='date and time of posting',
                        null=True,
                        verbose_name='postdate',
                    ),
                ),
                (
                    'info_customerdate',
                    models.DateTimeField(
                        help_text='client date and time',
                        null=True,
                        verbose_name='customerdate',
                    ),
                ),
                (
                    'info_ref',
                    models.CharField(
                        db_index=True,
                        help_text='banking reference',
                        max_length=40,
                        verbose_name='ref',
                    ),
                ),
                (
                    'info_state',
                    models.CharField(
                        blank=True,
                        choices=[('r', 'проведено'), ('t', 'сторнований')],
                        help_text='document state',
                        max_length=20,
                        null=True,
                        verbose_name='state of statement',
                    ),
                ),
                (
                    'info_flinfo',
                    models.CharField(
                        blank=True,
                        choices=[('r', 'real'), ('i', 'information')],
                        help_text='statement type',
                        max_length=20,
                        null=True,
                        verbose_name='type of statement',
                    ),
                ),
                (
                    'info_doctype',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('p', 'доручення'),
                            ('t', 'вимога'),
                            ('m', 'меморіальний ордер'),
                            ('x', 'прибутковий ордер'),
                            ('r', 'видатковий ордер'),
                        ],
                        help_text='document type',
                        max_length=20,
                        null=True,
                        verbose_name='type of document',
                    ),
                ),
                (
                    'amount_amt',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        help_text='amount of payment',
                        max_digits=17,
                        verbose_name='amount',
                    ),
                ),
                (
                    'amount_ccy',
                    models.CharField(
                        blank=True,
                        help_text='payment currency',
                        max_length=20,
                        null=True,
                        verbose_name='ccy',
                    ),
                ),
                (
                    'daccount_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='name of the customer',
                    ),
                ),
                (
                    'daccount_number',
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name='customer acc number',
                    ),
                ),
                (
                    'daccount_customer_crf',
                    models.CharField(
                        blank=True,
                        help_text='TIN / EDRPOU code of the customer',
                        max_length=20,
                        null=True,
                        verbose_name='customer crf',
                    ),
                ),
                (
                    'daccount_customer_bank_code',
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name='customer bank code',
                    ),
                ),
                (
                    'daccount_customer_bank_name',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name='customer bank name',
                    ),
                ),
                (
                    'caccount_name',
                    models.CharField(
                        blank=True,
                        help_text="recipient's name",
                        max_length=255,
                        null=True,
                        verbose_name='receiver name',
                    ),
                ),
                (
                    'caccount_number',
                    models.CharField(
                        blank=True,
                        help_text="beneficiary's account",
                        max_length=30,
                        null=True,
                        verbose_name='receiver acc number',
                    ),
                ),
                (
                    'caccount_customer_crf',
                    models.CharField(
                        blank=True,
                        help_text='TIN / EDRPOU code of the recipient',
                        max_length=20,
                        null=True,
                        verbose_name='receiver crf',
                    ),
                ),
                (
                    'caccount_customer_bank_code',
                    models.CharField(
                        blank=True,
                        help_text="MFI of the beneficiary's bank",
                        max_length=20,
                        null=True,
                        verbose_name='receiver bank code',
                    ),
                ),
                (
                    'caccount_customer_bank_name',
                    models.CharField(
                        blank=True,
                        help_text="the name of the recipient's bank",
                        max_length=255,
                        null=True,
                        verbose_name='recipient bank name',
                    ),
                ),
                (
                    'purpose',
                    models.TextField(
                        blank=True,
                        help_text='purpose of payment',
                        null=True,
                        verbose_name='purpose',
                    ),
                ),
                (
                    'is_find_invoice',
                    models.BooleanField(
                        default=False,
                        help_text='invoice number in purpose is founded',
                        verbose_name='find invoice',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
            },
        ),
    ]
