# Generated by Django 5.2 on 2025-04-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privat24api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='trantype',
            field=models.CharField(
                default='C',
                help_text='transaction type debit or credit: D or C',
                max_length=1,
                verbose_name='trantype',
            ),
        ),
    ]
