# Generated by Django 5.2 on 2025-04-04 01:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privat24api', '0002_statement_trantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='amount_amt_uah',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='amount of payment in native currency',
                max_digits=17,
                verbose_name='amount UAH',
            ),
        ),
        migrations.AddField(
            model_name='statement',
            name='btid',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='bank transaction id',
                max_length=20,
                null=True,
                verbose_name='bank id',
            ),
        ),
        migrations.AddField(
            model_name='statement',
            name='curency_iso',
            field=models.CharField(
                default='UAH',
                help_text='currency code',
                max_length=3,
                verbose_name='currency iso',
            ),
        ),
        migrations.AddField(
            model_name='statement',
            name='currency_exchange_at',
            field=models.DateField(null=True, verbose_name='currency exchanged'),
        ),
    ]
